### Stage 1
FROM python:3.12-slim AS builder

WORKDIR /app

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

RUN pip install --upgrade pip uv

COPY requirements.txt .

RUN pip install torch==2.2.2 \
    --index-url https://download.pytorch.org/whl/cpu

RUN uv pip install --no-cache-dir \
    "numpy<2" \
    "sentence-transformers==2.6.1" \
    -r requirements.txt


### Stage 2: Run Stage ###
FROM python:3.12-slim

WORKDIR /app

ENV PATH="/opt/venv/bin:$PATH"

COPY --from=builder /opt/venv /opt/venv

RUN adduser --disabled-password --gecos "" petops \
    && chown -R petops:petops /app

USER petops

COPY . .

EXPOSE 5007

CMD ["gunicorn", "-w", "1", "--timeout", "300", "-b", "0.0.0.0:5007", "app:app"]
